camera_name: azure_kinect  # ⚠️ 需要调整：改为"azure_kinect"

# ⚠️ 需要调整：Azure Kinect RGB相机默认分辨率为1920x1080，而非640x480
image_width: 1920  
image_height: 1080

camera_matrix:
  rows: 3
  cols: 3
  # ⚠️ 需要调整：这些是示例值，需要使用Azure Kinect的实际内参
  data: [ 600.0, 0.0, 320.0, 0.0, 600.0, 240.0, 0.0, 0.0, 1.0 ]

distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  # ⚠️ 需要调整：这些是示例值，需要使用Azure Kinect的实际畸变参数
  data: [ 0.1, -0.2, 0.0, 0.0, 0.0 ]

rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0 ]

projection_matrix:
  rows: 3
  cols: 4
  # ⚠️ 需要调整：这些是示例值，需要使用Azure Kinect的实际投影矩阵
  data: [ 600.0, 0.0, 320.0, 0.0, 0.0, 600.0, 240.0, 0.0, 0.0, 0.0, 1.0, 0.0 ]